// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PAFA.Infrastructure.Persistence;

#nullable disable

namespace PAFA.Infrastructure.Migrations
{
    [DbContext(typeof(PafaDbContext))]
    [Migration("20260326160109_InitUserRoleFixed")]
    partial class InitUserRoleFixed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MetricValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("IngestionFileId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("MetricKey")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("ProductClassCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("product_class_code");

                    b.Property<DateOnly>("ReportingPeriod")
                        .HasColumnType("date");

                    b.Property<byte[]>("RowVersion")
                        .HasColumnType("bytea");

                    b.Property<Guid?>("ShipperId")
                        .HasColumnType("uuid");

                    b.Property<string>("ShipperShortCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("TextValue")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric(12,4)");

                    b.HasKey("Id");

                    b.HasIndex("MetricKey")
                        .HasDatabaseName("ix_mv_metric_key");

                    b.HasIndex("ProductClassCode")
                        .HasDatabaseName("ix_mv_product_class");

                    b.HasIndex("ReportingPeriod")
                        .HasDatabaseName("ix_mv_period");

                    b.HasIndex("ShipperId");

                    b.HasIndex("ShipperShortCode")
                        .HasDatabaseName("ix_mv_ssc");

                    b.HasIndex("ReportingPeriod", "MetricKey")
                        .HasDatabaseName("ix_mv_period_key");

                    b.HasIndex("IngestionFileId", "ShipperShortCode", "ReportingPeriod", "MetricKey")
                        .IsUnique()
                        .HasDatabaseName("ix_mv_unique");

                    b.ToTable("metric_values", (string)null);
                });

            modelBuilder.Entity("PAFA.Domain.Entities.Authentication.PafaUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("pafa_users", (string)null);
                });

            modelBuilder.Entity("PAFA.Domain.Entities.Authentication.PafaUserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("pafa_user_roles", (string)null);
                });

            modelBuilder.Entity("PAFA.Domain.Entities.FactReadPerformance", b =>
                {
                    b.Property<decimal?>("CheckReadCount")
                        .HasColumnType("numeric")
                        .HasColumnName("check_read_count");

                    b.Property<decimal?>("EstimatedPct")
                        .HasColumnType("numeric")
                        .HasColumnName("estimated_pct");

                    b.Property<int>("IsCompliant")
                        .HasColumnType("integer")
                        .HasColumnName("is_compliant");

                    b.Property<string>("ProductClass")
                        .HasColumnType("text")
                        .HasColumnName("product_class");

                    b.Property<decimal?>("ReadPerfPct")
                        .HasColumnType("numeric")
                        .HasColumnName("read_perf_pct");

                    b.Property<string>("ReportMonth")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("report_month");

                    b.Property<string>("ShipperCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("shipper_code");

                    b.Property<decimal?>("TotalSites")
                        .HasColumnType("numeric")
                        .HasColumnName("total_sites");

                    b.ToTable((string)null);

                    b.ToView("fact_read_performance", (string)null);
                });

            modelBuilder.Entity("PAFA.Domain.Entities.IngestionFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("BlobPath")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("DownloadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ErrorCount")
                        .HasColumnType("integer");

                    b.Property<string>("FileHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<Guid>("IngestionJobId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea")
                        .HasDefaultValueSql("decode('', 'hex')");

                    b.Property<int?>("RowsRead")
                        .HasColumnType("integer");

                    b.Property<int?>("RowsRejected")
                        .HasColumnType("integer");

                    b.Property<int?>("RowsValid")
                        .HasColumnType("integer");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ValidationStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("FileHash")
                        .HasDatabaseName("ix_file_hash");

                    b.HasIndex("IngestionJobId");

                    b.ToTable("ingestion_files", (string)null);
                });

            modelBuilder.Entity("PAFA.Domain.Entities.IngestionJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ErrorSummary")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("FilesDownloaded")
                        .HasColumnType("integer");

                    b.Property<int?>("FilesExpected")
                        .HasColumnType("integer");

                    b.Property<int>("FilesFailed")
                        .HasColumnType("integer");

                    b.Property<int>("FilesProcessed")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("ParentJobId")
                        .HasColumnType("uuid");

                    b.Property<long>("RecordsLoaded")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("ReportingPeriod")
                        .HasColumnType("date");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("TriggeredBy")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ParentJobId");

                    b.HasIndex("ReportingPeriod")
                        .HasDatabaseName("ix_job_period");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_job_status");

                    b.ToTable("ingestion_jobs", (string)null);
                });

            modelBuilder.Entity("PAFA.Domain.Entities.Referential.ProductClass", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<decimal?>("AQThresholdHigh")
                        .HasColumnType("numeric(12,4)");

                    b.Property<decimal?>("AQThresholdLow")
                        .HasColumnType("numeric(12,4)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("MinReadPercentage")
                        .HasColumnType("numeric(6,3)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bytea");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_pc_code");

                    b.ToTable("product_classes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AQThresholdLow = 732m,
                            Code = "PC1",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SYSTEM",
                            Description = "Large sites — AQ ≥ 732 MWH",
                            IsActive = true,
                            IsDeleted = false,
                            MinReadPercentage = 97.5m
                        },
                        new
                        {
                            Id = 2,
                            Code = "PC2",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SYSTEM",
                            Description = "Medium NDM",
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 3,
                            Code = "PC3",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SYSTEM",
                            Description = "Small NDM WAR",
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 4,
                            Code = "PC4",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SYSTEM",
                            Description = "IGT Small",
                            IsActive = true,
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("PAFA.Domain.Entities.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Audience")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("CommentaryBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CommentaryText")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FilePath_Excel")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("FilePath_PDF")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("FilePath_PPTX")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsBaseline")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ReportTypeId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("ReportingPeriod")
                        .HasColumnType("date");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<int>("ScheduleNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_report_status");

                    b.HasIndex("ReportTypeId", "ReportingPeriod", "ScheduleNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_report_unique");

                    b.ToTable("reports", (string)null);
                });

            modelBuilder.Entity("PAFA.Domain.Entities.ReportType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Audience")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("ReportCount")
                        .HasColumnType("integer");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bytea");

                    b.Property<string>("ScheduleRef")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_reporttype_code");

                    b.ToTable("report_types", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Audience = "Industry",
                            Code = "SCH2A",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SYSTEM",
                            IsActive = true,
                            IsDeleted = false,
                            Label = "Industry Peer Comparison (Anonymised)",
                            ReportCount = 19,
                            ScheduleRef = "Schedule 2A"
                        },
                        new
                        {
                            Id = 2,
                            Audience = "PAC",
                            Code = "SCH2B",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SYSTEM",
                            IsActive = true,
                            IsDeleted = false,
                            Label = "Performance Assurance Committee (Non-Anonymised)",
                            ReportCount = 22,
                            ScheduleRef = "Schedule 2B"
                        });
                });

            modelBuilder.Entity("PAFA.Domain.Entities.ShipperProductClass", b =>
                {
                    b.Property<Guid>("ShipperId")
                        .HasColumnType("uuid");

                    b.Property<int>("ProductClassId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("ReportingPeriod")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea")
                        .HasDefaultValueSql("decode('', 'hex')");

                    b.Property<int?>("SupplyPointCount")
                        .HasColumnType("integer");

                    b.Property<decimal?>("TotalAQ_MWH")
                        .HasColumnType("numeric(14,4)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("ShipperId", "ProductClassId", "ReportingPeriod");

                    b.HasIndex("ProductClassId");

                    b.ToTable("shipper_product_classes", (string)null);
                });

            modelBuilder.Entity("PAFA.Domain.Entities.ValidationError", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ColumnName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ErrorCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("IngestionFileId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int?>("LineNumber")
                        .HasColumnType("integer");

                    b.Property<string>("OriginalValue")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("IngestionFileId")
                        .HasDatabaseName("ix_valerr_file");

                    b.ToTable("validation_errors", (string)null);
                });

            modelBuilder.Entity("PafaRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Role")
                        .IsUnique();

                    b.ToTable("pafa_roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Gemserv analyst — read reports",
                            Name = "PafaUser",
                            Role = "PAFA_USER"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Admin full access",
                            Name = "PafaAdmin",
                            Role = "PAFA_ADMIN"
                        },
                        new
                        {
                            Id = 3,
                            Description = "PAC access",
                            Name = "PacMember",
                            Role = "PAC_MEMBER"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Own data access",
                            Name = "Shipper",
                            Role = "SHIPPER"
                        });
                });

            modelBuilder.Entity("Shipper", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LegalEntity")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("legal_entity");

                    b.Property<DateOnly?>("MarketEntryDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("MarketExitDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<int?>("PortfolioSize")
                        .HasColumnType("integer");

                    b.Property<byte[]>("RowVersion")
                        .HasColumnType("bytea");

                    b.Property<string>("ShortCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("short_code");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ShortCode")
                        .IsUnique()
                        .HasDatabaseName("ix_shipper_short_code");

                    b.ToTable("shippers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SEED",
                            IsActive = true,
                            IsDeleted = false,
                            LegalEntity = "Alpha Gas Limited",
                            Name = "Alpha Gas Ltd",
                            ShortCode = "SHIP_A"
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SEED",
                            IsActive = true,
                            IsDeleted = false,
                            LegalEntity = "Beta Energy PLC",
                            Name = "Beta Energy plc",
                            ShortCode = "SHIP_B"
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SEED",
                            IsActive = true,
                            IsDeleted = false,
                            LegalEntity = "Gamma Supply Limited",
                            Name = "Gamma Supply Ltd",
                            ShortCode = "SHIP_C"
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SEED",
                            IsActive = true,
                            IsDeleted = false,
                            LegalEntity = "Delta Gas Company",
                            Name = "Delta Gas Co",
                            ShortCode = "SHIP_D"
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SEED",
                            IsActive = true,
                            IsDeleted = false,
                            LegalEntity = "Epsilon Energy Ltd",
                            Name = "Epsilon Energy",
                            ShortCode = "SHIP_E"
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SEED",
                            IsActive = true,
                            IsDeleted = false,
                            LegalEntity = "Zeta Gas Limited",
                            Name = "Zeta Gas Ltd",
                            ShortCode = "SHIP_F"
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000007"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SEED",
                            IsActive = true,
                            IsDeleted = false,
                            LegalEntity = "Eta Supply PLC",
                            Name = "Eta Supply plc",
                            ShortCode = "SHIP_G"
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000008"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SEED",
                            IsActive = true,
                            IsDeleted = false,
                            LegalEntity = "Theta Gas Corporation",
                            Name = "Theta Gas Corp",
                            ShortCode = "SHIP_H"
                        });
                });

            modelBuilder.Entity("MetricValue", b =>
                {
                    b.HasOne("PAFA.Domain.Entities.IngestionFile", "IngestionFile")
                        .WithMany("MetricValues")
                        .HasForeignKey("IngestionFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shipper", null)
                        .WithMany("MetricValues")
                        .HasForeignKey("ShipperId");

                    b.Navigation("IngestionFile");
                });

            modelBuilder.Entity("PAFA.Domain.Entities.Authentication.PafaUserRole", b =>
                {
                    b.HasOne("PafaRole", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PAFA.Domain.Entities.Authentication.PafaUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PAFA.Domain.Entities.IngestionFile", b =>
                {
                    b.HasOne("PAFA.Domain.Entities.IngestionJob", "IngestionJob")
                        .WithMany("IngestionFiles")
                        .HasForeignKey("IngestionJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IngestionJob");
                });

            modelBuilder.Entity("PAFA.Domain.Entities.IngestionJob", b =>
                {
                    b.HasOne("PAFA.Domain.Entities.IngestionJob", "ParentJob")
                        .WithMany("RetryJobs")
                        .HasForeignKey("ParentJobId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ParentJob");
                });

            modelBuilder.Entity("PAFA.Domain.Entities.Report", b =>
                {
                    b.HasOne("PAFA.Domain.Entities.ReportType", "ReportType")
                        .WithMany("Reports")
                        .HasForeignKey("ReportTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ReportType");
                });

            modelBuilder.Entity("PAFA.Domain.Entities.ShipperProductClass", b =>
                {
                    b.HasOne("PAFA.Domain.Entities.Referential.ProductClass", "ProductClass")
                        .WithMany("ShipperProductClasses")
                        .HasForeignKey("ProductClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Shipper", "Shipper")
                        .WithMany("ProductClasses")
                        .HasForeignKey("ShipperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductClass");

                    b.Navigation("Shipper");
                });

            modelBuilder.Entity("PAFA.Domain.Entities.ValidationError", b =>
                {
                    b.HasOne("PAFA.Domain.Entities.IngestionFile", "IngestionFile")
                        .WithMany("ValidationErrors")
                        .HasForeignKey("IngestionFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IngestionFile");
                });

            modelBuilder.Entity("PAFA.Domain.Entities.Authentication.PafaUser", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("PAFA.Domain.Entities.IngestionFile", b =>
                {
                    b.Navigation("MetricValues");

                    b.Navigation("ValidationErrors");
                });

            modelBuilder.Entity("PAFA.Domain.Entities.IngestionJob", b =>
                {
                    b.Navigation("IngestionFiles");

                    b.Navigation("RetryJobs");
                });

            modelBuilder.Entity("PAFA.Domain.Entities.Referential.ProductClass", b =>
                {
                    b.Navigation("ShipperProductClasses");
                });

            modelBuilder.Entity("PAFA.Domain.Entities.ReportType", b =>
                {
                    b.Navigation("Reports");
                });

            modelBuilder.Entity("PafaRole", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Shipper", b =>
                {
                    b.Navigation("MetricValues");

                    b.Navigation("ProductClasses");
                });
#pragma warning restore 612, 618
        }
    }
}
