// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PAFA.Infrastructure.Data;

#nullable disable

namespace PAFA.Infrastructure.Migrations
{
    [DbContext(typeof(PafaDbContext))]
    [Migration("20260310162319_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PAFA.Domain.Entities.ETL.IngestionJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorSummary")
                        .HasColumnType("text");

                    b.Property<int>("FilesDownloaded")
                        .HasColumnType("integer");

                    b.Property<int?>("FilesExpected")
                        .HasColumnType("integer");

                    b.Property<int>("FilesFailed")
                        .HasColumnType("integer");

                    b.Property<int>("FilesProcessed")
                        .HasColumnType("integer");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentJobId")
                        .HasColumnType("uuid");

                    b.Property<int>("PeriodMonth")
                        .HasColumnType("integer");

                    b.Property<int>("PeriodYear")
                        .HasColumnType("integer");

                    b.Property<long>("RecordsLoaded")
                        .HasColumnType("bigint");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("TriggeredBy")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParentJobId");

                    b.ToTable("IngestionJobs", "public");
                });

            modelBuilder.Entity("PAFA.Domain.Entities.IngestionFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("BlobPath")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Checksum")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DownloadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ErrorCount")
                        .HasColumnType("integer");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<Guid>("IngestionJobId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("RowVersion")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int?>("RowsRead")
                        .HasColumnType("integer");

                    b.Property<int?>("RowsRejected")
                        .HasColumnType("integer");

                    b.Property<int?>("RowsValid")
                        .HasColumnType("integer");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("CDSP");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("ValidationStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("IngestionJobId", "Status")
                        .HasDatabaseName("IX_IngestionFile_Job_Status");

                    b.ToTable("IngestionFile", "etl");
                });

            modelBuilder.Entity("PAFA.Domain.Entities.ProductClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AQThresholdHigh")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AQThresholdLow")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<decimal?>("MinReadPercentage")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UK_ProductClass_Code");

                    b.ToTable("ProductClass", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "PC1",
                            Description = "Class 1 – AQ > 732 MWH (Industrial, large sites)",
                            IsActive = true,
                            MinReadPercentage = 97.5m
                        },
                        new
                        {
                            Id = 2,
                            AQThresholdHigh = 732m,
                            AQThresholdLow = 73.2m,
                            Code = "PC2",
                            Description = "Class 2 – Quarterly read frequency",
                            IsActive = true
                        },
                        new
                        {
                            Id = 3,
                            AQThresholdHigh = 73.2m,
                            AQThresholdLow = 0m,
                            Code = "PC3",
                            Description = "Class 3 – Annual read frequency",
                            IsActive = true
                        },
                        new
                        {
                            Id = 4,
                            AQThresholdLow = 0m,
                            Code = "PC4",
                            Description = "Class 4 – Low read frequency / automated metering",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("PAFA.Domain.Entities.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("CommentaryBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CommentaryText")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("SYSTEM");

                    b.Property<string>("FilePath_Excel")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("FilePath_PDF")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("FilePath_PPTX")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsBaseline")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("PeriodMonth")
                        .HasColumnType("integer");

                    b.Property<int>("PeriodYear")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ReportTypeId")
                        .HasColumnType("integer");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<int>("ScheduleNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Pending");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Status", "GeneratedAt")
                        .HasDatabaseName("IX_Report_Status");

                    b.HasIndex("PeriodYear", "PeriodMonth", "ReportTypeId")
                        .HasDatabaseName("IX_Report_Period");

                    b.HasIndex("ReportTypeId", "ScheduleNumber", "PeriodYear", "PeriodMonth")
                        .IsUnique()
                        .HasDatabaseName("UK_Report_Type_Schedule_Period");

                    b.ToTable("Report", "dbo");
                });

            modelBuilder.Entity("PAFA.Domain.Entities.ReportType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsAnonymised")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("ReportCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("ScheduleRef")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UK_ReportType_Code");

                    b.ToTable("ReportType", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "SCH2A",
                            IsActive = true,
                            IsAnonymised = true,
                            Label = "Industry Peer Comparison View – Anonymised",
                            ReportCount = 19,
                            ScheduleRef = "Schedule 2A"
                        },
                        new
                        {
                            Id = 2,
                            Code = "SCH2B",
                            IsActive = true,
                            IsAnonymised = false,
                            Label = "Performance Assurance Committee View – Full",
                            ReportCount = 22,
                            ScheduleRef = "Schedule 2B"
                        });
                });

            modelBuilder.Entity("PAFA.Domain.Entities.Shipper", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<string>("ContactName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LegalEntity")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateOnly?>("MarketEntryDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("MarketExitDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("PortfolioSize")
                        .HasColumnType("integer");

                    b.Property<byte[]>("RowVersion")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("ShortCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Shipper_Name");

                    b.HasIndex("ShortCode")
                        .IsUnique()
                        .HasDatabaseName("UK_Shipper_ShortCode");

                    b.HasIndex("IsActive", "Name")
                        .HasDatabaseName("IX_Shipper_IsActive_Name");

                    b.ToTable("Shipper", "dbo");
                });

            modelBuilder.Entity("PAFA.Domain.Entities.ShipperAlias", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AliasCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("SYSTEM");

                    b.Property<Guid>("ShipperId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("ValidFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ValidTo")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("AliasCode")
                        .IsUnique()
                        .HasDatabaseName("UK_ShipperAlias_Code");

                    b.HasIndex("ShipperId", "ValidFrom", "ValidTo")
                        .HasDatabaseName("IX_ShipperAlias_ShipperId_Period");

                    b.ToTable("ShipperAlias", "dbo");
                });

            modelBuilder.Entity("PAFA.Domain.Entities.ShipperProductClass", b =>
                {
                    b.Property<Guid>("ShipperId")
                        .HasColumnType("uuid");

                    b.Property<int>("ProductClassId")
                        .HasColumnType("integer");

                    b.Property<int>("PeriodYear")
                        .HasColumnType("integer");

                    b.Property<int>("PeriodMonth")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<int?>("SupplyPointCount")
                        .HasColumnType("integer");

                    b.Property<decimal?>("TotalAQ_MWH")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ShipperId", "ProductClassId", "PeriodYear", "PeriodMonth");

                    b.HasIndex("ProductClassId");

                    b.HasIndex("ShipperId", "PeriodYear", "PeriodMonth")
                        .HasDatabaseName("IX_ShipperProductClass_Shipper_Period");

                    b.ToTable("ShipperProductClass", "dbo");
                });

            modelBuilder.Entity("PAFA.Domain.Entities.ValidationError", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ColumnName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<string>("ErrorCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("IngestionFileId")
                        .HasColumnType("uuid");

                    b.Property<int?>("LineNumber")
                        .HasColumnType("integer");

                    b.Property<string>("OriginalValue")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("ERROR");

                    b.HasKey("Id");

                    b.HasIndex("IngestionFileId", "Severity")
                        .HasDatabaseName("IX_ValidationError_File_Severity");

                    b.ToTable("ValidationError", "etl");
                });

            modelBuilder.Entity("PAFA.Domain.Entities.ETL.IngestionJob", b =>
                {
                    b.HasOne("PAFA.Domain.Entities.ETL.IngestionJob", "ParentJob")
                        .WithMany("ChildJobs")
                        .HasForeignKey("ParentJobId");

                    b.Navigation("ParentJob");
                });

            modelBuilder.Entity("PAFA.Domain.Entities.IngestionFile", b =>
                {
                    b.HasOne("PAFA.Domain.Entities.ETL.IngestionJob", "IngestionJob")
                        .WithMany("Files")
                        .HasForeignKey("IngestionJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_IngestionFile_IngestionJob");

                    b.Navigation("IngestionJob");
                });

            modelBuilder.Entity("PAFA.Domain.Entities.Report", b =>
                {
                    b.HasOne("PAFA.Domain.Entities.ReportType", "ReportType")
                        .WithMany("Reports")
                        .HasForeignKey("ReportTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Report_ReportType");

                    b.Navigation("ReportType");
                });

            modelBuilder.Entity("PAFA.Domain.Entities.ShipperAlias", b =>
                {
                    b.HasOne("PAFA.Domain.Entities.Shipper", "Shipper")
                        .WithMany("Aliases")
                        .HasForeignKey("ShipperId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ShipperAlias_Shipper");

                    b.Navigation("Shipper");
                });

            modelBuilder.Entity("PAFA.Domain.Entities.ShipperProductClass", b =>
                {
                    b.HasOne("PAFA.Domain.Entities.ProductClass", "ProductClass")
                        .WithMany("ShipperProductClasses")
                        .HasForeignKey("ProductClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ShipperProductClass_ProductClass");

                    b.HasOne("PAFA.Domain.Entities.Shipper", "Shipper")
                        .WithMany("ProductClasses")
                        .HasForeignKey("ShipperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ShipperProductClass_Shipper");

                    b.Navigation("ProductClass");

                    b.Navigation("Shipper");
                });

            modelBuilder.Entity("PAFA.Domain.Entities.ValidationError", b =>
                {
                    b.HasOne("PAFA.Domain.Entities.IngestionFile", "IngestionFile")
                        .WithMany("ValidationErrors")
                        .HasForeignKey("IngestionFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ValidationError_IngestionFile");

                    b.Navigation("IngestionFile");
                });

            modelBuilder.Entity("PAFA.Domain.Entities.ETL.IngestionJob", b =>
                {
                    b.Navigation("ChildJobs");

                    b.Navigation("Files");
                });

            modelBuilder.Entity("PAFA.Domain.Entities.IngestionFile", b =>
                {
                    b.Navigation("ValidationErrors");
                });

            modelBuilder.Entity("PAFA.Domain.Entities.ProductClass", b =>
                {
                    b.Navigation("ShipperProductClasses");
                });

            modelBuilder.Entity("PAFA.Domain.Entities.ReportType", b =>
                {
                    b.Navigation("Reports");
                });

            modelBuilder.Entity("PAFA.Domain.Entities.Shipper", b =>
                {
                    b.Navigation("Aliases");

                    b.Navigation("ProductClasses");
                });
#pragma warning restore 612, 618
        }
    }
}
