<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<ProduceReferenceAssembly>false</ProduceReferenceAssembly>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\PAFA.Domain\PAFA.Domain.csproj" />
		<ProjectReference Include="..\PAFA.Infrastructure\PAFA.Infrastructure.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="FluentValidation" Version="11.11.0" />
		<PackageReference Include="MediatR" Version="12.*" />
		<PackageReference Include="Microsoft.AspNetCore.Http" Version="2.3.9" />
	</ItemGroup>

</Project>