using PAFA.Domain.Enums;

namespace PAFA.Domain.Entities;

/// <summary>
/// Monthly instance of a PARR report generated by the system.
/// References PDF/Excel files stored on Azure Blob Storage.
/// </summary>
public class Report : BaseEntity
{
    public Guid   Id             { get; set; } = Guid.NewGuid();

    public int    ReportTypeId   { get; set; }

    /// <summary>Report number within the schedule (1 to 22).</summary>
    public int    ScheduleNumber { get; set; }

    /// <summary>Full title (e.g., "2A.1 Estimated & Check Reads – Products 1 & 2").</summary>
    public string Title          { get; set; } = string.Empty;

    public int    PeriodYear     { get; set; }

    /// <summary>Reporting month (1–12).</summary>
    public int    PeriodMonth    { get; set; }

    public ReportStatus Status   { get; set; } = ReportStatus.Pending;

    public DateTime?  GeneratedAt  { get; set; }
    public DateTime?  PublishedAt  { get; set; }

    /// <summary>Azure Blob path to the generated PDF file.</summary>
    public string? FilePath_PDF   { get; set; }

    /// <summary>Azure Blob path to the generated Excel file.</summary>
    public string? FilePath_Excel { get; set; }

    /// <summary>Azure Blob path to the PowerPoint dashboard (optional).</summary>
    public string? FilePath_PPTX  { get; set; }

    /// <summary>Editorial commentary from PAFA analyst for this report.</summary>
    public string? CommentaryText { get; set; }
    public string? CommentaryBy   { get; set; }

    /// <summary>True = baseline report used for YoY comparisons.</summary>
    public bool    IsBaseline     { get; set; } = false;

    // ── Navigation ──────────────────────────────────────────────────────
    public ReportType                  ReportType   { get; set; } = null!;
}